{% set name = "dagster-cloud" %}
{% set version = "1.8.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dagster-cloud-{{ version }}.tar.gz
  sha256: a1ebde26b11feef443811ca71ca37054f9e360251a18b2e6f083920793e41e36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - dagster =={{ version }}
    - dagster-cloud-cli =={{ version }}
    - pex >=2.1.132,<3
    - questionary
    - requests
    - typer

test:
  imports:
    - dagster_cloud
  commands:
    - pip check
  requires:
    - pip

about:
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/dagster-io/dagster-cloud
  summary: Cloud support for Dagster

extra:
  recipe-maintainers:
    - jaiswal-ankur
    - geoHeil
    - tmirko
    - milicevica23
