schema_version: 1

context:
  python_min: '3.10'
  name: dagster-cloud
  version: "1.13.15"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 7a703411f84a716792bef03922fa5daf8aaa380abd9f16d6b5da77b79d77863b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.19.0
  run:
    - python >=${{ python_min }}
    - dagster ==${{ version }}
    - dagster-cloud-cli ==${{ version }}
    - dagster-shared ==${{ version }}
    - pex >=2.1.132,<2.60.0
    - questionary
    - requests
    - typer >=0.15.0

tests:
  - python:
      imports:
        - dagster_cloud
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Cloud support for Dagster
  homepage: https://github.com/dagster-io/dagster-cloud

extra:
  recipe-maintainers:
    - jaiswal-ankur
    - geoHeil
    - tmirko
    - milicevica23
